kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: plugins/hugo
    settings:
      hugo_version: 0.95
      validate: true
    commands:
    - apk add libc6-compat libstdc++
    - /bin/drone-hugo


