baseurl = "https://blog.kedare.net/"
title = "Kedare / Mathieu Poussin's Engineering Blog"
languageCode = "en-us"
theme = "hugo_theme_robust"
disqusShortname = "kedare-blog"
uglyurls = true

[params]
  contact = "mathieu.poussin@netyxia.net"
