baseurl = "https://blog.kedare.net/"
title = "Kedare / Mathieu Poussin's Engineering Blog"
languageCode = "en-us"
theme = "hugo_theme_robust"
disqusShortname = "kedare-blog"
uglyurls = true
googleAnalytics = "UA-48657517-2"
enableRobotsTXT = true

[params]
  contact = "mathieu.poussin@netyxia.net"
  custom_css = ["css/custom.css"]
