baseurl = "https://blog.kedare.net/"
title = "Kedare / Mathieu Poussin's Tech Blog"
languageCode = "en-us"
theme = "hugo_theme_robust"
disqusShortname = "kedare-blog"
uglyurls = true
googleAnalytics = "UA-48657517-2"
enableRobotsTXT = false

[markup.goldmark.renderer]
unsafe= true

[author]
  name = "Mathieu Poussin"
  email = "blog@mpouss.in"

[params]
  contact = "blog@mpouss.in"
  custom_css = ["css/custom.css"]
