jobs:
  deploy:
    executor: azure-cli/default
    steps:
      - attach_workspace:
          at: output/
      - run: ls -lah output/
  verify-azure-cli:
    executor: azure-cli/default
    steps:
      - azure-cli/install
      - run:
          command: az -v
          name: Verify Azure CLI is installed
orbs:
  hugo: circleci/hugo@0.2
  azure-cli: circleci/azure-cli@1.2.2
version: 2.1
workflows:
  main:
    jobs:
      - verify-azure-cli
      - hugo/build:
          html-proofer: true
          source: ./
          version: '0.95'
          requires:
            - verify-azure-cli
      - deploy:
          requires:
            - hugo/build
            - verify-azure-cli