jobs:
  deploy:
    docker:
      - image: cimg/base
    steps:
      - attach_workspace:
          at: output/
      - run: ls -lah output/
orbs:
  hugo: circleci/hugo@0.2
version: 2.1
workflows:
  main:
    jobs:
      - hugo/build:
          html-proofer: true
          source: ./
          version: '0.95'
      - deploy:
          filters:
            branches:
              only: master
          requires:
            - hugo/build