name: Build Hugo website

on:
  push:

jobs:
  build:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.95.0'
          extended: true

      - name: Build with Hugo
        run: hugo --minify
      
      - name: Compress
        run: tar cjvf website.tar.bz2 public/

      - name: Upload website
        uses: actions/upload-artifact@v2
        with:
          name: website
          path: website.tar.bz2
  
  deploy:
    needs: [build]
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-20.04
    container: 
      image: rclone/rclone:1.58
    steps:
      - name: Download website
        uses: actions/download-artifact@v2
        with:
          name: website

      - name: Decompress
        run: tar xvf website.tar.bz2

      - name: Configure credentials
        shell: sh
        env:
            BLOG_STORAGE_NAME: ${{ secrets.BLOG_STORAGE_NAME }}
            BLOG_STORAGE_KEY: ${{ secrets.BLOG_STORAGE_KEY }}
        run: 'rclone config create blog azureblob account="$BLOG_STORAGE_NAME" key="$BLOG_STORAGE_KEY"'
        
      - name: Push website to bucket
        run: 'rclone -v sync "public/" "blog:/\$web/"'
