name: Deploy Hugo site to Firebase

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["master"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read

# Allow one concurrent deployment
concurrency:
  group: "publish"
  cancel-in-progress: true

# Default to bash
defaults:
  run:
    shell: bash

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.144.0
    steps:
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.144.2'
          extended: true
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Build with Hugo
        run: |
          hugo --minify
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEDARE_BLOG }}
          channelId: live
          projectId: kedare-blog
